import { Footer, Header } from "@/components/UI";

export const metadata = { title: "Termos de Uso", description: "Regras gerais de uso da plataforma Rede Conecta." };
export default function Terms() {
  return <><Header/><main><section className="legal"><div className="container"><span className="eyebrow">Versão 2026-07-27</span><h1>Termos Gerais de Uso da Rede Conecta</h1><p>Estes Termos regulam o acesso e a utilização da plataforma Rede Conecta por visitantes, conectores, equipe interna, corretores, empreendedores, incorporadores, loteadores e demais parceiros autorizados.</p>
  <h2>1. Modelo operacional</h2><p>A Rede Conecta organiza conexões originadas por produtos específicos, registra consentimentos, preserva a origem, conduz o atendimento e acompanha o ciclo comercial. Os painéis e permissões variam conforme o perfil. A operação de leads, contatos, tarefas, propostas, negócios e recompensas é centralizada na Rede Conecta.</p>
  <h2>2. Conta e segurança</h2><p>O usuário deverá fornecer informações verdadeiras, proteger sua senha, utilizar autenticação própria e informar qualquer acesso indevido. Contas, convites e links de ativação são pessoais e intransferíveis. A Rede Conecta poderá suspender acessos por risco, fraude, violação destes Termos, exigência legal ou término da relação contratual.</p>
  <h2>3. Consentimento e produto de origem</h2><p>O interessado recebe um convite relacionado a um produto determinado. O contato comercial somente é iniciado após autorização registrada. A apresentação de alternativas depende de autorização adicional quando prevista no fluxo. O produto, a campanha, o conector e o momento de origem permanecem registrados e não podem ser substituídos por usuários externos.</p>
  <h2>4. Conteúdo e informações comerciais</h2><p>Materiais, preços, disponibilidade, condições, imagens e documentos devem ser aqueles aprovados e publicados na plataforma. Informações podem mudar e não constituem promessa de disponibilidade, valorização, rentabilidade, aprovação de crédito ou conclusão de negócio.</p>
  <h2>5. Condutas proibidas</h2><p>É proibido cadastrar dados sem autorização; criar identidade falsa; manipular atribuições; realizar autoindicação artificial; compartilhar credenciais; extrair dados; contornar controles; usar informações para abordar diretamente leads protegidos; ocultar vendas; desviar negócios; alterar materiais oficiais; prometer resultados; receber valores em nome da Rede Conecta sem autorização; ou utilizar a plataforma para atividade ilegal.</p>
  <h2>6. Intermediação imobiliária</h2><p>Atividades privativas de corretor de imóveis deverão ser exercidas por profissional ou pessoa jurídica devidamente habilitados. O conector não habilitado limita-se à aproximação inicial por materiais e links oficiais, sem negociar preço, condições, documentos ou fechamento.</p>
  <h2>7. Recompensas</h2><p>Recompensas de conectores são regidas pela versão da campanha registrada no momento da conexão. Valores apresentados como potenciais somente se tornam elegíveis após o evento definido, validação comercial e financeira, ausência de impedimento, documentação necessária e demais condições da regra aplicável.</p>
  <h2>8. Parceiros e não circunvenção</h2><p>Parceiros reconhecem que leads e negócios originados pela Rede Conecta permanecem protegidos durante a janela registrada. É vedado abordar o lead fora do fluxo, ocultar proposta, reserva, contrato, pagamento ou venda, transferir o relacionamento para terceiro ou criar registro paralelo com a finalidade de suprimir atribuição, remuneração ou auditoria.</p>
  <h2>9. Disponibilidade e mudanças</h2><p>A plataforma poderá receber atualizações, manutenções, integrações e alterações de recursos. A Rede Conecta buscará continuidade e integridade, sem garantir funcionamento ininterrupto de redes, mensageiros, provedores de e-mail, pagamentos ou serviços de terceiros.</p>
  <h2>10. Propriedade intelectual</h2><p>A marca, os sistemas, layouts, textos, fluxos, bases, relatórios e materiais da Rede Conecta são protegidos. O uso é limitado às finalidades autorizadas e não transfere titularidade ou licença além do necessário ao serviço.</p>
  <h2>11. Responsabilidade</h2><p>Cada usuário responde por seus atos, informações, promessas, acessos e violações. A existência da plataforma não substitui análise jurídica, documental, urbanística, financeira, técnica, tributária ou profissional relacionada ao imóvel e ao negócio.</p>
  <h2>12. Registros e prova</h2><p>Logs de acesso, consentimentos, históricos, alterações de status, auditorias, mensagens transacionais, documentos e registros de conciliação poderão ser utilizados para segurança, apuração, cumprimento contratual e exercício de direitos.</p>
  <h2>13. Disposições finais</h2><p>Termos específicos de conectores, parceiros, corretores, campanhas e privacidade complementam este documento. Em conflito, prevalece a regra específica aplicável à relação e à versão registrada.</p>
  <div className="legal-note">A entidade responsável pela operação deverá inserir sua qualificação societária, canal de atendimento e foro contratual antes da campanha pública definitiva. A aceitação eletrônica registra versão, data, usuário e contexto.</div></div></section></main><Footer/></>;
}
