import { Footer, Header } from "@/components/UI";

export const metadata = { title: "Política de Recompensas", description: "Critérios de elegibilidade, aprovação, pagamento e contestação das recompensas." };
export default function RewardPolicy() {
  return <><Header/><main><section className="legal"><div className="container"><span className="eyebrow">Versão 2026-07-27</span><h1>Política de Recompensas da Rede Conecta</h1><p>Esta política define a linguagem e os controles gerais das recompensas de conectores. A regra específica de cada campanha prevalece quanto a valor, evento qualificante, vigência, janela de atribuição e documentação.</p>
  <h2>1. Estados da recompensa</h2><p><b>Potencial</b> indica negócio ainda não elegível. <b>Pendente</b> indica evento informado e em análise. <b>Aprovada</b> indica condições validadas. <b>Programada</b> indica pagamento agendado. <b>Paga</b> indica transferência confirmada. <b>Cancelada</b> indica perda de elegibilidade, cancelamento do negócio, fraude, duplicidade ou outro impedimento fundamentado.</p>
  <h2>2. Evento qualificante</h2><p>O evento poderá incluir contrato assinado, pagamento inicial compensado, ausência de cancelamento durante o período definido, validação documental, conciliação com o parceiro e regularidade cadastral do conector. Reserva, visita ou proposta não geram pagamento salvo se a campanha declarar expressamente o contrário.</p>
  <h2>3. Atribuição</h2><p>A recompensa depende da origem válida e da janela registrada. Quando houver conversão em produto diferente, aplica-se a regra de venda cruzada da campanha e da organização. Conflitos são resolvidos pela linha do tempo, consentimento, histórico operacional, atendimento prévio e evidências.</p>
  <h2>4. Aprovação e pagamento</h2><p>A equipe comercial valida o negócio, o financeiro valida os requisitos e o sistema registra aprovações, ajustes, programação e comprovantes. Pagamentos dependem de dados bancários ou chave válida, documentação fiscal ou recibo quando aplicável e inexistência de bloqueio de compliance.</p>
  <h2>5. Ajustes e estornos</h2><p>Registros pagos não são apagados. Correções são realizadas por lançamento de ajuste ou estorno, com motivo, responsável e auditoria. Cancelamento, desfazimento, fraude, devolução ou informação falsa podem justificar reversão nos limites contratuais e legais.</p>
  <h2>6. Contestação</h2><p>O conector poderá contestar duplicidade, rejeição, valor, ausência de atribuição ou pagamento. A plataforma gera protocolo e preserva evidências. A decisão informa fundamento e poderá ser revista quando surgirem documentos relevantes.</p>
  <h2>7. Tributos e documentos</h2><p>Cada recebedor é responsável por fornecer dados corretos e cumprir suas obrigações. Retenções, recibos, notas fiscais e classificação contábil dependem da natureza da relação, do perfil do recebedor e da orientação profissional aplicável.</p>
  <div className="legal-note">A recompensa por conexão não autoriza o conector a realizar intermediação imobiliária nem substitui a remuneração profissional de corretores habilitados.</div></div></section></main><Footer/></>;
}
