import { Footer, Header } from "@/components/UI";

export const metadata = { title: "Termos dos Parceiros", description: "Regras de acesso, leitura, não circunvenção e conciliação para parceiros da Rede Conecta." };
export default function PartnerTerms() {
  return <><Header/><main><section className="legal"><div className="container"><span className="eyebrow">Versão 2026-07-27</span><h1>Termos de Parceiros e Não Circunvenção</h1><p>Estes termos disciplinam o acesso de loteadoras, incorporadoras, imobiliárias, construtoras, terrenistas e demais parceiros aos dados e relatórios da Rede Conecta. O instrumento comercial assinado entre as partes complementa este documento.</p>
  <h2>1. Operação centralizada</h2><p>A Rede Conecta recebe a autorização do interessado, distribui internamente o atendimento, registra atividades, conduz a qualificação e acompanha o negócio. O parceiro recebe informações executivas, comerciais e financeiras compatíveis com sua finalidade, sem acesso automático a dados pessoais, documentos, mensagens ou anotações internas dos leads.</p>
  <h2>2. Origem e janela de proteção</h2><p>Cada conexão registra campanha, produto, conector, data, consentimento e janela de proteção. Durante a janela aplicável, toda reserva, proposta, contrato, pagamento, venda direta, venda por corretor, troca de produto ou negócio relacionado ao interessado deverá ser informado e conciliado com a Rede Conecta.</p>
  <h2>3. Não circunvenção</h2><p>O parceiro, suas coligadas, sócios, funcionários, corretores, prestadores e representantes não poderão abordar o lead fora do fluxo autorizado; criar cadastro paralelo para apagar a origem; transferir a oportunidade; suprimir a Rede Conecta; ocultar andamento; alterar data; atribuir a venda a outra fonte; ou estruturar negócio com a finalidade de evitar remuneração, recompensa, comissão, taxa ou auditoria.</p>
  <h2>4. Uso dos painéis</h2><p>Os painéis são de leitura. Informações agregadas sobre protocolos, etapas, produtos, datas, proteção e valores não autorizam contato direto. Exportações, capturas e relatórios deverão ser usados apenas para gestão do empreendimento e preservados contra acesso indevido.</p>
  <h2>5. Corretores vinculados</h2><p>Corretores cadastrados pelo parceiro recebem acesso individual e restrito. A vinculação a produtos não transfere a operação do lead. O parceiro responde por instruir seus profissionais, comunicar suspensões, preservar credenciais e não compartilhar acessos.</p>
  <h2>6. Reconciliação de vendas</h2><p>Quando exigido, o parceiro deverá enviar periodicamente relação de reservas, contratos, cancelamentos e vendas, com os campos necessários à conciliação. A plataforma poderá comparar identificadores protegidos, protocolos, datas, unidades e valores, gerando alertas de divergência sem expor os dados dos demais usuários.</p>
  <h2>7. Evidências e auditoria</h2><p>A Rede Conecta poderá solicitar contratos, comprovantes, relatórios, histórico de CRM, documentos de reserva e outras evidências necessárias à validação. Alterações, acessos, aceites, importações e resoluções ficam registrados em auditoria.</p>
  <h2>8. Incidentes e comunicação</h2><p>O parceiro deverá comunicar imediatamente suspeita de vazamento, uso indevido, abordagem não autorizada, conflito de atribuição ou venda não conciliada. A cooperação inclui preservação de evidências e cumprimento das orientações de segurança e proteção de dados.</p>
  <h2>9. Consequências</h2><p>A violação poderá resultar em bloqueio de acesso, suspensão de campanhas, preservação ou extensão da atribuição, cobrança dos valores devidos, indenização, aplicação das penalidades contratuais e exercício de direitos pelas vias cabíveis.</p>
  <h2>10. Aceite</h2><p>O usuário autorizado aceita estes termos em nome próprio e declara possuir poderes ou autorização para representar o parceiro na finalidade informada. O aceite eletrônico não substitui o contrato empresarial quando este for exigido.</p>
  <div className="legal-note">Valores, penalidades, foro, exclusividade, obrigação de conciliação e prazo de proteção devem constar também no contrato comercial específico firmado com cada parceiro.</div></div></section></main><Footer/></>;
}
