import { Footer, Header } from "@/components/UI";

export const metadata = { title: "Termos do Conector", description: "Regras para cadastro, atuação e recompensa dos conectores da Rede Conecta." };
export default function ConnectorTerms() {
  return <><Header/><main><section className="legal"><div className="container"><span className="eyebrow">Versão 2026-07-27</span><h1>Termos Específicos do Conector</h1><p>O conector é a pessoa aprovada pela Rede Conecta para compartilhar oportunidades oficiais com sua rede de relacionamento. Estes termos complementam os Termos Gerais e a Política de Privacidade.</p>
  <h2>1. Cadastro e aprovação</h2><p>O cadastro direto não garante aprovação. A Rede Conecta poderá validar identidade, contato, cidade, atividade, qualidade da rede, histórico, conformidade e risco. O perfil permanece pendente até a aprovação interna e a confirmação oficial.</p>
  <h2>2. Atuação permitida</h2><p>O conector poderá escolher produtos liberados, gerar links individualizados, escrever uma mensagem pessoal, usar materiais oficiais e acompanhar status e recompensas em seu painel. A conexão deve decorrer de relacionamento legítimo e respeitar a privacidade do destinatário.</p>
  <h2>3. Limites de atuação</h2><p>O conector não atua como corretor, representante, mandatário ou empregado da Rede Conecta. Não poderá negociar preço ou condições, apresentar proposta, aconselhar sobre compra, prometer valorização, conduzir visita profissional, coletar documentos da negociação, receber sinais ou pagamentos, alterar materiais ou declarar garantia de aprovação ou fechamento.</p>
  <h2>4. Convites e consentimento</h2><p>O conector deverá encaminhar o link oficial ao próprio interessado. O atendimento depende de autorização concedida no link. É proibido cadastrar telefone, e-mail ou dados de terceiro sem base legítima, induzir aceite ou ocultar que poderá existir recompensa pela origem do negócio.</p>
  <h2>5. Atribuição</h2><p>A atribuição considera o primeiro registro válido, a campanha, o produto, o consentimento, a janela de proteção, duplicidades, relacionamento anterior e regras vigentes. O conector não poderá criar cadastros repetidos, trocar dados, combinar registros ou pressionar o interessado para manipular a atribuição.</p>
  <h2>6. Recompensa</h2><p>O valor e as condições são definidos por campanha. O painel poderá mostrar recompensa potencial, pendente, aprovada, programada, paga, cancelada ou objeto de contestação. A exigibilidade depende do evento qualificante, validações, ausência de cancelamento, documentação e regularidade cadastral e fiscal aplicáveis.</p>
  <h2>7. Condutas vedadas</h2><p>São vedados spam, listas compradas, abordagem enganosa, criação de perfis falsos, autoindicação artificial, compartilhamento de conteúdo impróprio, uso de marca não autorizado, concorrência desleal, contato com menores sem necessidade e salvaguardas, tratamento indevido de dados, promessa de renda, cobrança do interessado e qualquer tentativa de burlar a operação.</p>
  <h2>8. Suspensão e encerramento</h2><p>A Rede Conecta poderá suspender links, campanhas ou conta por risco, denúncia, fraude, inatividade, descumprimento, exigência regulatória ou término da rede. Recompensas já elegíveis serão analisadas conforme a regra registrada e as evidências disponíveis.</p>
  <h2>9. Responsabilidade</h2><p>O conector responde pela veracidade de seus dados, pela mensagem pessoal que escreve e pelo modo como apresenta o convite. A assinatura oficial de origem e segurança não deve ser removida ou adulterada.</p>
  <h2>10. Aceite</h2><p>O aceite eletrônico registra versão, data, usuário e contexto. Alterações relevantes poderão exigir novo aceite antes da geração de links.</p>
  <div className="legal-note">A nomenclatura e o tratamento fiscal da recompensa deverão seguir os contratos e a orientação jurídica e contábil da entidade operadora.</div></div></section></main><Footer/></>;
}
