import { Footer, Header } from "@/components/UI";

export const metadata = { title: "Política de Privacidade", description: "Como a Rede Conecta coleta, utiliza, protege e compartilha dados pessoais." };
export default function Privacy() {
  return <><Header/><main><section className="legal"><div className="container"><span className="eyebrow">Versão 2026-07-27</span><h1>Política de Privacidade da Rede Conecta</h1><p>Esta política explica como a Rede Conecta trata dados pessoais em seus sites, convites, formulários, painéis, CRM, comunicações e processos de recompensa. O tratamento é orientado por finalidade, necessidade, transparência, segurança e responsabilização.</p>
  <h2>1. Quem participa do tratamento</h2><p>A Rede Conecta conduz a operação da plataforma e define os fluxos de cadastro, autorização, atendimento, gestão comercial, auditoria e recompensas. Loteadoras, incorporadoras, imobiliárias, corretores, provedores de tecnologia e comunicação podem atuar dentro de escopos contratuais e de acesso definidos. A qualificação jurídica de controlador, controlador conjunto ou operador depende da atividade e do contrato aplicável.</p>
  <h2>2. Dados tratados</h2><p>Podemos tratar dados de identificação e contato, cidade e estado, profissão, informações sobre a rede de relacionamentos, preferências imobiliárias, registros de consentimento, origem do convite, eventos de acesso e compartilhamento, histórico de atendimento, tarefas, compromissos, propostas, documentos de negócio, dados necessários ao pagamento de recompensas e registros técnicos de segurança.</p>
  <h2>3. Finalidades</h2><p>Os dados são usados para criar e proteger contas; analisar e aprovar conectores; apresentar o produto específico compartilhado; obter autorização antes do atendimento; prevenir duplicidades e fraudes; distribuir e conduzir leads; registrar negócios e recompensas; enviar comunicações operacionais; cumprir obrigações legais e contratuais; conciliar vendas de parceiros; preservar a origem das oportunidades; atender direitos dos titulares; e manter segurança e auditoria.</p>
  <h2>4. Bases legais e consentimentos</h2><p>O tratamento poderá se apoiar em consentimento, execução de contrato ou procedimentos preliminares, cumprimento de obrigação legal ou regulatória, exercício regular de direitos, prevenção à fraude, proteção do crédito e legítimo interesse, conforme o contexto. Consentimentos de marketing e de investigação de outras oportunidades são separados do consentimento necessário ao atendimento do produto de origem.</p>
  <h2>5. Compartilhamento e limitação de acesso</h2><p>Dados pessoais são disponibilizados somente a usuários autorizados e na medida necessária à função. Empreendedores e corretores recebem painéis de leitura sem acesso automático a nome, telefone, e-mail, documentos, conversas ou anotações internas de leads. O contato e a operação comercial permanecem sob controle da Rede Conecta, salvo concessão expressa, registrada e revogável.</p>
  <h2>6. Armazenamento, segurança e auditoria</h2><p>Aplicamos autenticação, sessões protegidas, permissões por função, segregação de ambientes, controle por registro, trilhas de auditoria, links temporários para documentos privados, registros imutáveis de origem e monitoramento de eventos críticos. Nenhum sistema é absolutamente imune a incidentes; quando aplicável, serão adotadas medidas de contenção, investigação e comunicação.</p>
  <h2>7. Retenção</h2><p>Os dados são mantidos pelo tempo necessário às finalidades informadas, à preservação de direitos, ao cumprimento de obrigações legais, à prevenção de fraudes, à auditoria e à solução de controvérsias. Convites não utilizados, candidaturas rejeitadas e informações sem finalidade ativa poderão ser eliminados ou anonimizados segundo a política interna de retenção.</p>
  <h2>8. Direitos do titular</h2><p>O titular poderá solicitar confirmação do tratamento, acesso, correção, informação sobre compartilhamentos, anonimização, bloqueio ou eliminação quando cabível, portabilidade nos limites aplicáveis, revisão de decisões automatizadas, oposição e revogação de consentimento. A solicitação poderá exigir validação de identidade e será atendida pelo canal de privacidade disponibilizado na plataforma.</p>
  <h2>9. Comunicações</h2><p>Mensagens operacionais sobre cadastro, autorização, atendimento, segurança, negócio ou recompensa podem ser necessárias à execução do serviço. Comunicações promocionais dependem de base legal apropriada e podem ser desativadas sem impedir mensagens essenciais.</p>
  <h2>10. Atualizações</h2><p>Esta política poderá ser atualizada para refletir mudanças operacionais, tecnológicas ou regulatórias. A versão aceita pelo usuário fica registrada quando o aceite é necessário.</p>
  <div className="legal-note">Para solicitações de privacidade, utilize o canal oficial de suporte e privacidade informado dentro da plataforma. Esta versão operacional deve permanecer alinhada aos contratos da entidade responsável e à avaliação jurídica aplicável.</div></div></section></main><Footer/></>;
}
